<div style="text-align: center; margin: 30px auto; max-width: 600px;">
    <div style="background: linear-gradient(135deg, #F39C12, #D35400); width: 80px; height: 2px; margin: 0 auto;"></div>
    <h1 style="color: #D35400; font-family: 'Times New Roman', Times, serif; font-size: 1.6em; margin: 10px 0; font-weight: 600; text-transform: uppercase; letter-spacing: 4px;"> Projet de stage </h1>
    <h2 style="color: #F39C12; font-family: 'Times New Roman', Times, serif; font-size: 1.1em; margin: 0; font-style: italic; letter-spacing: 1px;">fin d'étude</h2>
    <div style="background: linear-gradient(135deg, #F39C12, #D35400); width: 50px; height: 2px; margin: 10px auto;"></div>
</div>

<div style="max-width: 990px; margin: 20px auto;">
    <div style="background: #F39C12; padding: 5px; border-radius: 20px; box-shadow: 8px 8px 0 #FFF0D4;">
        <div style="background: linear-gradient(135deg, #F39C12, #D35400); padding: 4px; border-radius: 17px;">
            <div style="background: #FFFEF7; border-radius: 14px;">
                <h1 align="center" style="
                    color: #D35400;
                    font-family: 'Times New Roman', Times, serif; 
                    font-size: 2em;
                    font-weight: bold;
                    margin: 0;
                    text-shadow: 1px 1px 0 #FDEBD0;
                    letter-spacing: 2px;
                ">
                     Système Intelligent d'Optimisation<br>et de Gestion des Stocks - Bijouterie 
                </h1>
            </div>
        </div>
    </div>
</div>

<div align="center" style="font-family: 'Times New Roman', Times, serif; color: #5D4E37;">
    <h3 style="margin: 0; color: black;">Filière : BSDSI</h3>
</div>

<br>

<div align="center" style="font-family: 'Times New Roman', Times, serif; color: #5D4E37;">
    <b>Réalisée par :</b><br>
    IKSOD Salma
</div>

<br>

<div align="center" style="font-family: 'Times New Roman', Times, serif; color: #5D4E37;">
    <b>Année universitaire</b><br>
    2025-2026
</div>

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Importation des librairies :</h1>

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore') #pour masquer les messages inutiles

# ── Visualisation statique
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns

# ── Visualisation interactive
import plotly.express as px    # !pip install plotly
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ── Configuration graphique globale
plt.rcParams['figure.figsize'] = (14, 6)
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12
sns.set_style('whitegrid')
sns.set_palette('Set2')

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Chargement du dataset :</h1>

In [7]:
df = pd.read_csv(r"C:\Users\DELL\OneDrive - OFPPT\Bureau\Intelligent-Stock-Optimization-Platform\Data\dataset_stock_bijou_expert_ml.csv")
df

,date,article_id,depot_id,categorie,matiere,ville,stock_initial,achat_qte,vente_qte,stock_final,...,annee,mois,jour_semaine,is_weekend,moyenne_vente_7j,moyenne_vente_30j,rotation_stock,couverture_stock,rupture_stock,surstock
0,2024-01-01,ART_001,DEPOT_1,Montre,Argent,Agadir,99,5,14,90,...,2024,1,0,0,14.000000,14.000000,0.140000,6.000000,0,0
1,2024-01-02,ART_001,DEPOT_1,Boucles,Acier,Marrakech,129,15,7,137,...,2024,1,1,0,10.500000,10.500000,0.053846,11.913043,0,0
2,2024-01-03,ART_001,DEPOT_1,Montre,Argent,Casablanca,100,9,11,98,...,2024,1,2,0,10.666667,10.666667,0.108911,8.400000,0,0
3,2024-01-04,ART_001,DEPOT_1,Bracelet,Or,Rabat,33,5,11,27,...,2024,1,3,0,10.750000,10.750000,0.323529,2.297872,0,0
4,2024-01-05,ART_001,DEPOT_1,Bague,Acier,Casablanca,67,8,5,70,...,2024,1,4,0,9.600000,9.600000,0.073529,6.603774,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204475,2026-04-27,ART_060,DEPOT_4,Bracelet,Or,Marrakech,59,8,12,55,...,2026,4,0,0,7.428571,7.466667,0.200000,6.525424,0,0
204476,2026-04-28,ART_060,DEPOT_4,Bracelet,Argent,Agadir,41,10,6,45,...,2026,4,1,0,7.714286,7.466667,0.142857,5.163934,0,0
204477,2026-04-29,ART_060,DEPOT_4,Collier,Acier,Rabat,62,10,6,66,...,2026,4,2,0,7.714286,7.366667,0.095238,7.573770,0,0
204478,2026-04-30,ART_060,DEPOT_4,Bague,Or,Marrakech,131,6,10,127,...,2026,4,3,0,8.000000,7.466667,0.075758,14.111111,0,0
204479,2026-05-01,ART_060,DEPOT_4,Boucles,Or,Casablanca,91,10,11,90,...,2026,5,4,0,8.285714,7.500000,0.119565,9.692308,0,0

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration des données :</h1>

<div style="background: linear-gradient(to right, #D3540020, #FEF5E8); padding: 12px 20px; border-bottom: 3px solid #D35400; max-width: 1350px; font-family: 'Times New Roman'; margin-bottom: 15px;">
    <p style="font-family: 'Times New Roman'; font-size: 1.4em; font-weight: bold; color: #F39C12; margin: 0; text-shadow: 0 0 2px rgba(211,84,0,0.2);">
         1 - Aperçu des 5 dernières lignes : 
    </p>
</div>

In [12]:
print(f'   → Nombre de lignes    : {df.shape[0]:,}')
print(f'   → Nombre de colonnes  : {df.shape[1]}')
print()
print('── Aperçu des 5 premières lignes ──')
df.head()

   → Nombre de lignes    : 204,480
   → Nombre de colonnes  : 24

── Aperçu des 5 premières lignes ──

,date,article_id,depot_id,categorie,matiere,ville,stock_initial,achat_qte,vente_qte,stock_final,...,annee,mois,jour_semaine,is_weekend,moyenne_vente_7j,moyenne_vente_30j,rotation_stock,couverture_stock,rupture_stock,surstock
0,2024-01-01,ART_001,DEPOT_1,Montre,Argent,Agadir,99,5,14,90,...,2024,1,0,0,14.000000,14.000000,0.140000,6.000000,0,0
1,2024-01-02,ART_001,DEPOT_1,Boucles,Acier,Marrakech,129,15,7,137,...,2024,1,1,0,10.500000,10.500000,0.053846,11.913043,0,0
2,2024-01-03,ART_001,DEPOT_1,Montre,Argent,Casablanca,100,9,11,98,...,2024,1,2,0,10.666667,10.666667,0.108911,8.400000,0,0
3,2024-01-04,ART_001,DEPOT_1,Bracelet,Or,Rabat,33,5,11,27,...,2024,1,3,0,10.750000,10.750000,0.323529,2.297872,0,0
4,2024-01-05,ART_001,DEPOT_1,Bague,Acier,Casablanca,67,8,5,70,...,2024,1,4,0,9.600000,9.600000,0.073529,6.603774,0,0

<div style="background: linear-gradient(to right, #D3540020, #FEF5E8); padding: 12px 20px; border-bottom: 3px solid #D35400; max-width: 1350px; font-family: 'Times New Roman'; margin-bottom: 15px;">
    <p style="font-family: 'Times New Roman'; font-size: 1.4em; font-weight: bold; color: #F39C12; margin: 0; text-shadow: 0 0 2px rgba(211,84,0,0.2);">
         2 - Aperçu des 5 dernières lignes : 
    </p>
</div>

In [10]:
print('── Aperçu des 5 dernières lignes ──')
df.tail()

── Aperçu des 5 dernières lignes ──

,date,article_id,depot_id,categorie,matiere,ville,stock_initial,achat_qte,vente_qte,stock_final,...,annee,mois,jour_semaine,is_weekend,moyenne_vente_7j,moyenne_vente_30j,rotation_stock,couverture_stock,rupture_stock,surstock
204475,2026-04-27,ART_060,DEPOT_4,Bracelet,Or,Marrakech,59,8,12,55,...,2026,4,0,0,7.428571,7.466667,0.200000,6.525424,0,0
204476,2026-04-28,ART_060,DEPOT_4,Bracelet,Argent,Agadir,41,10,6,45,...,2026,4,1,0,7.714286,7.466667,0.142857,5.163934,0,0
204477,2026-04-29,ART_060,DEPOT_4,Collier,Acier,Rabat,62,10,6,66,...,2026,4,2,0,7.714286,7.366667,0.095238,7.573770,0,0
204478,2026-04-30,ART_060,DEPOT_4,Bague,Or,Marrakech,131,6,10,127,...,2026,4,3,0,8.000000,7.466667,0.075758,14.111111,0,0
204479,2026-05-01,ART_060,DEPOT_4,Boucles,Or,Casablanca,91,10,11,90,...,2026,5,4,0,8.285714,7.500000,0.119565,9.692308,0,0

<div style="background: linear-gradient(to right, #D3540020, #FEF5E8); padding: 12px 20px; border-bottom: 3px solid #D35400; max-width: 1350px; font-family: 'Times New Roman'; margin-bottom: 15px;">
    <p style="font-family: 'Times New Roman'; font-size: 1.4em; font-weight: bold; color: #F39C12; margin: 0; text-shadow: 0 0 2px rgba(211,84,0,0.2);">
         3 - Échantillon aléatoire de 5 lignes :  
    </p>
</div>

In [11]:
# ── Échantillon aléatoire de 5 lignes (vue transversale du dataset)
print('── Échantillon aléatoire de 5 lignes ──')
df.sample(5, random_state=42)

── Échantillon aléatoire de 5 lignes ──

,date,article_id,depot_id,categorie,matiere,ville,stock_initial,achat_qte,vente_qte,stock_final,...,annee,mois,jour_semaine,is_weekend,moyenne_vente_7j,moyenne_vente_30j,rotation_stock,couverture_stock,rupture_stock,surstock
162994,2024-09-19,ART_048,DEPOT_4,Bracelet,Or,Agadir,150,8,13,145,...,2024,9,3,0,8.714286,8.300000,0.086093,14.926471,0,0
104104,2024-06-09,ART_031,DEPOT_3,Collier,Acier,Casablanca,88,13,9,92,...,2024,6,6,1,9.285714,8.366667,0.101124,8.944444,0,0
172523,2025-02-23,ART_051,DEPOT_3,Collier,Or,Marrakech,49,9,6,52,...,2025,2,6,1,8.428571,7.433333,0.120000,5.515152,0,0
136771,2025-03-27,ART_041,DEPOT_1,Bracelet,Or,Rabat,72,10,4,78,...,2025,3,3,0,5.857143,7.066667,0.054795,11.375000,0,0
53723,2024-02-17,ART_016,DEPOT_4,Bague,Or,Rabat,56,7,8,55,...,2024,2,5,1,8.571429,8.166667,0.140351,5.746269,0,0

<div style="background: linear-gradient(to right, #D3540020, #FEF5E8); padding: 12px 20px; border-bottom: 3px solid #D35400; max-width: 1350px; font-family: 'Times New Roman'; margin-bottom: 15px;">
    <p style="font-family: 'Times New Roman'; font-size: 1.4em; font-weight: bold; color: #F39C12; margin: 0; text-shadow: 0 0 2px rgba(211,84,0,0.2);">
         4 - Structure et types des données :  
    </p>
</div>

In [13]:
# ── Informations générales sur le DataFrame
print('── Informations structurelles du DataFrame ──')
df.info()

── Informations structurelles du DataFrame ──
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204480 entries, 0 to 204479
Data columns (total 24 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   date               204480 non-null  object
 1   article_id         204480 non-null  object
 2   depot_id           204480 non-null  object
 3   categorie          204480 non-null  object
 4   matiere            204480 non-null  object
 5   ville              204480 non-null  object
 6   stock_initial      204480 non-null  int64
 7   achat_qte          204480 non-null  int64
 8   vente_qte          204480 non-null  int64
 9   stock_final        204480 non-null  int64
 10  stock_systeme      204480 non-null  int64
 11  ecart_stock        204480 non-null  int64
 12  prix_achat         204480 non-null  float64
 13  prix_vente         204480 non-null  float64
 14  annee              204480 non-null  int64
 15  mois               204480 non-null  int64
 16  jour_semaine       204480 non-null  int64
 17  is_weekend         204480 non-null  int64
 18  moyenne_vente_7j   204480 non-null  float64
 19  moyenne_vente_30j  204480 non-null  float64
 20  rotation_stock     204480 non-null  float64
 21  couverture_stock   204480 non-null  float64
 22  rupture_stock      204480 non-null  int64
 23  surstock           204480 non-null  int64
dtypes: float64(6), int64(12), object(6)
memory usage: 37.4+ MB

In [16]:
# ── Résumé des types de données par colonne
type_summary = pd.DataFrame({
    'Colonne'     : df.columns,
    'Type Python' : df.dtypes.values,
    'Exemples'    : [str(df[col].unique()[:3].tolist()) for col in df.columns]
})

print('── Types de données et exemples de valeurs ──')
display(type_summary)

print()
print(f' Observation ⚠️ : la colonne "date" est de type STRING → à convertir en datetime en Phase 2')

── Types de données et exemples de valeurs ──

,Colonne,Type Python,Exemples
0,date,object,"['2024-01-01', '2024-01-02', '2024-01-03']"
1,article_id,object,"['ART_001', 'ART_002', 'ART_003']"
2,depot_id,object,"['DEPOT_1', 'DEPOT_2', 'DEPOT_3']"
3,categorie,object,"['Montre', 'Boucles', 'Bracelet']"
4,matiere,object,"['Argent', 'Acier', 'Or']"
5,ville,object,"['Agadir', 'Marrakech', 'Casablanca']"
6,stock_initial,int64,"[99, 129, 100]"
7,achat_qte,int64,"[5, 15, 9]"
8,vente_qte,int64,"[14, 7, 11]"
9,stock_final,int64,"[90, 137, 98]"
10,stock_systeme,int64,"[87, 136, 100]"
11,ecart_stock,int64,"[3, 1, -2]"
12,prix_achat,float64,"[392.5164197814674, 364.2902781342101, 117.079..."
13,prix_vente,float64,"[627.861132969784, 452.2018627794762, 152.8978..."
14,annee,int64,"[2024, 2025, 2026]"
15,mois,int64,"[1, 2, 3]"
16,jour_semaine,int64,"[0, 1, 2]"
17,is_weekend,int64,"[0, 1]"
18,moyenne_vente_7j,float64,"[14.0, 10.5, 10.666666666666666]"
19,moyenne_vente_30j,float64,"[14.0, 10.5, 10.666666666666666]"
20,rotation_stock,float64,"[0.14, 0.0538461538461538, 0.1089108910891089]"
21,couverture_stock,float64,"[6.0, 11.91304347826087, 8.4]"
22,rupture_stock,int64,[0]
23,surstock,int64,"[0, 1]"

 Observation ⚠️ : la colonne "date" est de type STRING → à convertir en datetime en Phase 2

<div style="background: linear-gradient(to right, #D3540020, #FEF5E8); padding: 12px 20px; border-bottom: 3px solid #D35400; max-width: 1350px; font-family: 'Times New Roman'; margin-bottom: 15px;">
    <p style="font-family: 'Times New Roman'; font-size: 1.4em; font-weight: bold; color: #F39C12; margin: 0; text-shadow: 0 0 2px rgba(211,84,0,0.2);">
         5 - Le dictionnaire des colonnes  :  
    </p>
</div>

In [17]:
# ── Dictionnaire des colonnes avec leur signification métier
dictionnaire = {
    'date'             : 'Date de la transaction (format YYYY-MM-DD)',
    'article_id'       : 'Identifiant unique de l article (ART_001 → ART_060)',
    'depot_id'         : 'Identifiant du dépôt (DEPOT_1 → DEPOT_4)',
    'categorie'        : 'Catégorie du bijou : Montre, Bague, Collier, Boucles, Bracelet',
    'matiere'          : 'Matière du bijou : Or, Argent, Acier',
    'ville'            : 'Ville du dépôt : Agadir, Marrakech, Casablanca, Rabat',
    'stock_initial'    : 'Stock disponible en début de journée',
    'achat_qte'        : 'Quantité achetée/réapprovisionnée ce jour',
    'vente_qte'        : 'Quantité vendue ce jour (variable cible principale)',
    'stock_final'      : 'Stock disponible en fin de journée',
    'stock_systeme'    : 'Stock enregistré dans le système informatique',
    'ecart_stock'      : 'Différence entre stock réel et système (détection anomalies)',
    'prix_achat'       : 'Prix d achat unitaire (MAD)',
    'prix_vente'       : 'Prix de vente unitaire (MAD)',
    'annee'            : 'Année extraite de la date',
    'mois'             : 'Mois extrait de la date (1–12)',
    'jour_semaine'     : 'Jour de la semaine (0=Lundi → 6=Dimanche)',
    'is_weekend'       : 'Indicateur weekend (1=Oui, 0=Non)',
    'moyenne_vente_7j' : 'Moyenne des ventes sur les 7 derniers jours',
    'moyenne_vente_30j': 'Moyenne des ventes sur les 30 derniers jours',
    'rotation_stock'   : 'Taux de rotation = ventes / stock (plus élevé = mieux)',
    'couverture_stock' : 'Nombre de jours couverts par le stock actuel',
    'rupture_stock'    : 'Indicateur de rupture de stock (1=Rupture, 0=Normal)',
    'surstock'         : 'Indicateur de surstock (1=Surstock, 0=Normal)'
}
df_dict = pd.DataFrame(list(dictionnaire.items()),columns=['Colonne', 'Description métier', ])
print('── Dictionnaire des variables ──')
display(df_dict)

── Dictionnaire des variables ──

              Colonne                                 Description métier
0                date         Date de la transaction (format YYYY-MM-DD)
1          article_id  Identifiant unique de l article (ART_001 → ART...
2            depot_id           Identifiant du dépôt (DEPOT_1 → DEPOT_4)
3           categorie  Catégorie du bijou : Montre, Bague, Collier, B...
4             matiere               Matière du bijou : Or, Argent, Acier
5               ville  Ville du dépôt : Agadir, Marrakech, Casablanca...
6       stock_initial               Stock disponible en début de journée
7           achat_qte          Quantité achetée/réapprovisionnée ce jour
8           vente_qte  Quantité vendue ce jour (variable cible princi...
9         stock_final                 Stock disponible en fin de journée
10      stock_systeme      Stock enregistré dans le système informatique
11        ecart_stock  Différence entre stock réel et système (détect...
12         prix_achat                        Prix d achat unitaire (MAD)
13         prix_vente                       Prix de vente unitaire (MAD)
14              annee                          Année extraite de la date
15               mois                     Mois extrait de la date (1–12)
16       jour_semaine          Jour de la semaine (0=Lundi → 6=Dimanche)
17         is_weekend                  Indicateur weekend (1=Oui, 0=Non)
18   moyenne_vente_7j        Moyenne des ventes sur les 7 derniers jours
19  moyenne_vente_30j       Moyenne des ventes sur les 30 derniers jours
20     rotation_stock  Taux de rotation = ventes / stock (plus élevé ...
21   couverture_stock       Nombre de jours couverts par le stock actuel
22      rupture_stock  Indicateur de rupture de stock (1=Rupture, 0=N...
23           surstock      Indicateur de surstock (1=Surstock, 0=Normal)

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration des données :</h1>

<h3 style="color: #F39C12; font-weight: bold; font-family: 'Times New Roman'; text-align: left;">1- Affichage des premières lignes :</h3>

<h3 style="color: #F39C12; font-weight: bold; font-family: 'Times New Roman'; text-align: left;">1- Affichage des premières lignes :</h3>

<h3 style="color: #F39C12; font-weight: bold; font-family: 'Times New Roman'; text-align: left;">1- Affichage des premières lignes :</h3>

<h3 style="color: #F39C12; font-weight: bold; font-family: 'Times New Roman'; text-align: left;">1- Affichage des premières lignes :</h3>

<h3 style="color: #F39C12; font-weight: bold; font-family: 'Times New Roman'; text-align: left;">1- Affichage des premières lignes :</h3>

<h3 style="color: #F39C12; font-weight: bold; font-family: 'Times New Roman'; text-align: left;">1- Affichage des premières lignes :</h3>

<h3 style="color: #F39C12; font-weight: bold; font-family: 'Times New Roman'; text-align: left;">1- Affichage des premières lignes :</h3>

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration du dataset :</h1>

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration du dataset :</h1>

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration du dataset :</h1>

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration du dataset :</h1>

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration du dataset :</h1>

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration du dataset :</h1>

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration du dataset :</h1>

<h1 style="color: #D35400; font-weight: bold; font-family: 'Times New Roman';">🟠 Exploration du dataset :</h1>